resources:
  cpus: 1
  # Add GPUs here

envs:
  DATA_BUCKET_URL: s3://sky-demo-data
  NUM_EPOCHS: 2

file_mounts:
  /data:
    source: $DATA_BUCKET_URL

setup: |
  echo "Setting up dependencies for training..."

run: |
  echo "Running training..."
  
  # Run a mock training job that loops through the files in /data starting with 'file_'
  for (( i=1; i<=NUM_EPOCHS; i++ )); do
    for file in /data/file_*; do
      echo "Epoch $i: Training on $file"
      sleep 2
    done
  done
  
  # Mock checkpointing the trained model to the data bucket
  echo "Trained model" > /data/trained_model.txt
  
  echo "Training completed, model written to to $DATA_BUCKET_URL"
